- name: Ensure that consul_config_template is defined
  assert:
    that:
      - consul_config_template
    fail_msg: "'consul_config_template' must be defined"

- name: Updating Apt Cache
  apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Installing dependencies
  apt:
    name:
      - unzip
    state: present
  become: true
  register: result
  until: result is successful
