- name: Configuring Consul service
  template:
    src: etc/systemd/system/consul.service.j2
    dest: /etc/systemd/system/consul.service
    owner: root
    group: root
    mode: 0664
  become: true
  notify:
    - reload systemd
    - restart consul

- name: Ensuring Consul service is enabled
  service:
    name: consul
    enabled: true
  become: true
